=== Zacle/practicecoding/test/query.schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "title": "Test Query",
    "description": "A test query and its expected response when passed to Interface.performQuery",
    "type": "object",
    "properties": {
        "title": {
            "description": "A meaningful test name that describes the query",
            "type": "string",
            "minLength": 5,
            "maxLength": 100
        },
        "plateform": {
            "description": "The palteform to query"
        },
        "query": {
            "description": "The query that will be sent to performQuery"
        },
        "response": {
            "description": "The expected response from performQuery",
            "type": "object",
            "properties": {
                "code": {
                    "type": "number"
                },
                "body": {
                    "type": "object"
                }
            },
            "additionalProperties": false,
            "required": ["code", "body"]
        }
    },
    "additionalProperties": false,
    "required": ["title", "query", "plateform", "response"]
}

=== Zacle/practicecoding/test/queries/q17.json
{
    "title": "SELECT All problems that contain 'er' ",
    "query": "er",
    "plateform": "all",
    "response": {
        "code": 200,
        "body": {
            "result": [
                {
                    "id": 1033,
                    "name": "F. Boolean Computer",
                    "plateform": "Codeforces",
                    "link": "https://codeforces.com/problemset/problem/1033/F"
                },
                {
                    "id": 1036,
                    "name": "E. Covered Points",
                    "plateform": "Codeforces",
                    "link": "https://codeforces.com/problemset/problem/1036/E"
                },
                {
                    "id": 993,
                    "name": "E. Nikita and Order Statistics",
                    "plateform": "Codeforces",
                    "link": "https://codeforces.com/problemset/problem/993/E"
                },
                {
                    "id": 986,
                    "name": "D. Perfect Encoding",
                    "plateform": "Codeforces",
                    "link": "https://codeforces.com/problemset/problem/986/D"
                },
                {
                    "id": 958,
                    "name": "F3. Lightsabers (hard)",
                    "plateform": "Codeforces",
                    "link": "https://codeforces.com/problemset/problem/958/F3"
                },
                {
                    "id": 954,
                    "name": "I. Yet Another String Matching Problem",
                    "plateform": "Codeforces",
                    "link": "https://codeforces.com/problemset/problem/954/I"
                },
                {
                    "id": 923,
                    "name": "E. Perpetual Substraction",
                    "plateform": "Codeforces",
                    "link": "https://codeforces.com/problemset/problem/923/E"
                },
                {
                    "id": 901,
                    "name": "E. Cyclic Cipher",
                    "plateform": "Codeforces",
                    "link": "https://codeforces.com/problemset/problem/901/E"
                },
                {
                    "id": 773,
                    "name": "F. Test Data Generation",
                    "plateform": "Codeforces",
                    "link": "https://codeforces.com/problemset/problem/773/F"
                },
                {
                    "id": 715,
                    "name": "E. Complete the Permutations",
                    "plateform": "Codeforces",
                    "link": "https://codeforces.com/problemset/problem/715/E"
                },
                {
                    "id": 2,
                    "name": "2001 - Compiler code generation",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=2"
                },
                {
                    "id": 8,
                    "name": "2007 - Tag Checker",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=8"
                },
                {
                    "id": 15,
                    "name": "2014 - Are We There Yet?",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=15"
                },
                {
                    "id": 24,
                    "name": "2023 - Who Wants to Have the Fastest Fingers?",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=24"
                },
                {
                    "id": 27,
                    "name": "2026 - Generating permutations",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=27"
                },
                {
                    "id": 42,
                    "name": "106 – Fermat vs. Pythagoras",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=42"
                },
                {
                    "id": 45,
                    "name": "109 – SCUD Busters",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=45"
                },
                {
                    "id": 49,
                    "name": "113 – Power of Cryptography",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=49"
                },
                {
                    "id": 53,
                    "name": "117 - The Postal Worker Rings Once",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=53"
                },
                {
                    "id": 54,
                    "name": "118 - Mutant Flatworld Explorers",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=54"
                },
                {
                    "id": 55,
                    "name": "119 - Greedy Gift Givers",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=55"
                },
                {
                    "id": 57,
                    "name": "121 - Pipe Fitters",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=57"
                },
                {
                    "id": 60,
                    "name": "124 - Following Orders",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=60"
                },
                {
                    "id": 61,
                    "name": "125 - Numbering Paths",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=61"
                },
                {
                    "id": 62,
                    "name": "126 - The Errant Physicist",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=62"
                }
            ]
        }
    }
}

=== Zacle/practicecoding/test/queries/filter/q6.json
{
    "title": "SELECT Live Archive hard problems",
    "query": "hard",
    "plateform": "livearchive",
    "response": {
        "code": 200,
        "body": {
            "result": [
                {
                    "id": "1",
                    "name": "2000 – Wrap it up",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=1"
                },
                {
                    "id": "2",
                    "name": "2001 - Compiler code generation",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=2"
                },
                {
                    "id": "3",
                    "name": "2002 – Crosswords",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=3"
                },
                {
                    "id": "4",
                    "name": "2003 - Genetic family tree",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=4"
                },
                {
                    "id": "5",
                    "name": "2004 - Fire trucks",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=5"
                },
                {
                    "id": "10",
                    "name": "2009 - Best Image Layout",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=10"
                },
                {
                    "id": "11",
                    "name": "2010 - Swiss Draw",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=11"
                },
                {
                    "id": "12",
                    "name": "2011 – Calypso",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=12"
                },
                {
                    "id": "13",
                    "name": "2012 - Four in a Line",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=13"
                },
                {
                    "id": "17",
                    "name": "2016 - Charity Begins at Home-page",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=17"
                },
                {
                    "id": "19",
                    "name": "2018 - If it's a Javelin  Duck!",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=19"
                },
                {
                    "id": "20",
                    "name": "2019 - The Party's in Dolores's Driveway",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=20"
                },
                {
                    "id": "21",
                    "name": "2020 - Programming Olympiad",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=21"
                },
                {
                    "id": "23",
                    "name": "2022 - The Plane Problem",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=23"
                },
                {
                    "id": "24",
                    "name": "2023 - Who Wants to Have the Fastest Fingers?",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=24"
                },
                {
                    "id": "25",
                    "name": "2024 – Convoy",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=25"
                },
                {
                    "id": "26",
                    "name": "2025 - Digital Lab",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=26"
                },
                {
                    "id": "29",
                    "name": "2028 - Treasure Hunt",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=29"
                }
            ]
        }
    }
}

=== Zacle/practicecoding/test/queries/filter/q9.json
{
    "title": "SELECT Uva hard problems",
    "query": "hard",
    "plateform": "uva",
    "response": {
        "code": 200,
        "body": {
            "result": [
                {
                    "id": "40",
                    "name": "104 – Arbitrage",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=40"
                },
                {
                    "id": "52",
                    "name": "116 – Unidirectional TSP",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=52"
                },
                {
                    "id": "61",
                    "name": "125 - Numbering Paths",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=61"
                }
            ]
        }
    }
}

=== Zacle/practicecoding/test/queries/query/q4.json
{
    "title": "SELECT Codeforces problems that contain 'ered' ",
    "query": "ered",
    "plateform": "codeforces",
    "response": {
        "code": 200,
        "body": {
            "result": [
                {
                    "id": "1036",
                    "name": "E. Covered Points",
                    "plateform": "Codeforces",
                    "link": "https://codeforces.com/problemset/problem/1036/E"
                }
            ]
        }
    }
}

=== Zacle/practicecoding/test/queries/query/q2.json
{
    "title": "SELECT Codeforces problems that contain 'er' ",
    "query": "er",
    "plateform": "codeforces",
    "response": {
        "code": 200,
        "body": {
            "result": [
                {
                    "id": "1033",
                    "name": "F. Boolean Computer",
                    "plateform": "Codeforces",
                    "link": "https://codeforces.com/problemset/problem/1033/F"
                },
                {
                    "id": "1036",
                    "name": "E. Covered Points",
                    "plateform": "Codeforces",
                    "link": "https://codeforces.com/problemset/problem/1036/E"
                },
                {
                    "id": "993",
                    "name": "E. Nikita and Order Statistics",
                    "plateform": "Codeforces",
                    "link": "https://codeforces.com/problemset/problem/993/E"
                },
                {
                    "id": "986",
                    "name": "D. Perfect Encoding",
                    "plateform": "Codeforces",
                    "link": "https://codeforces.com/problemset/problem/986/D"
                },
                {
                    "id": "958",
                    "name": "F3. Lightsabers (hard)",
                    "plateform": "Codeforces",
                    "link": "https://codeforces.com/problemset/problem/958/F3"
                },
                {
                    "id": "954",
                    "name": "I. Yet Another String Matching Problem",
                    "plateform": "Codeforces",
                    "link": "https://codeforces.com/problemset/problem/954/I"
                },
                {
                    "id": "923",
                    "name": "E. Perpetual Substraction",
                    "plateform": "Codeforces",
                    "link": "https://codeforces.com/problemset/problem/923/E"
                },
                {
                    "id": "901",
                    "name": "E. Cyclic Cipher",
                    "plateform": "Codeforces",
                    "link": "https://codeforces.com/problemset/problem/901/E"
                },
                {
                    "id": "773",
                    "name": "F. Test Data Generation",
                    "plateform": "Codeforces",
                    "link": "https://codeforces.com/problemset/problem/773/F"
                },
                {
                    "id": "755",
                    "name": "G. PolandBall And Many Other Balls",
                    "plateform": "Codeforces",
                    "link": "https://codeforces.com/problemset/problem/755/G"
                },
                {
                    "id": "715",
                    "name": "E. Complete the Permutations",
                    "plateform": "Codeforces",
                    "link": "https://codeforces.com/problemset/problem/715/E"
                }
            ]
        }
    }
}

=== Zacle/practicecoding/test/queries/q18.json
{
    "title": "SELECT All problems that contain 'ere' ",
    "query": "ere",
    "plateform": "all",
    "response": {
        "code": 200,
        "body": {
            "result": [
                {
                    "id": 1036,
                    "name": "E. Covered Points",
                    "plateform": "Codeforces",
                    "link": "https://codeforces.com/problemset/problem/1036/E"
                },
                {
                    "id": 15,
                    "name": "2014 - Are We There Yet?",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=15"
                }
            ]
        }
    }
}

=== Zacle/practicecoding/test/queries/filter/q8.json
{
    "title": "SELECT Uva medium problems",
    "query": "medium",
    "plateform": "uva",
    "response": {
        "code": 200,
        "body": {
            "result": [
                {
                    "id": "36",
                    "name": "100 – The 3n + 1 problem",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=36"
                },
                {
                    "id": "37",
                    "name": "101 - The Block Problem",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=37"
                },
                {
                    "id": "38",
                    "name": "102 – Ecological Bin Packing",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=38"
                },
                {
                    "id": "39",
                    "name": "103 – Stacking Boxes",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=39"
                },
                {
                    "id": "41",
                    "name": "105 – The Skyline Problem",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=41"
                },
                {
                    "id": "42",
                    "name": "106 – Fermat vs. Pythagoras",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=42"
                },
                {
                    "id": "43",
                    "name": "107 – The Cat in the Hat",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=43"
                },
                {
                    "id": "44",
                    "name": "108 – Maximun Sum",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=44"
                },
                {
                    "id": "45",
                    "name": "109 – SCUD Busters",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=45"
                },
                {
                    "id": "46",
                    "name": "110 – Meta-Loopless Sorts",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=46"
                },
                {
                    "id": "47",
                    "name": "111 – History Grading",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=47"
                },
                {
                    "id": "48",
                    "name": "112 – Tree Summing",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=48"
                },
                {
                    "id": "49",
                    "name": "113 – Power of Cryptography",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=49"
                },
                {
                    "id": "50",
                    "name": "114 – Simulation Wizardry",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=50"
                },
                {
                    "id": "51",
                    "name": "115 – Climbing Trees",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=51"
                },
                {
                    "id": "53",
                    "name": "117 - The Postal Worker Rings Once",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=53"
                },
                {
                    "id": "54",
                    "name": "118 - Mutant Flatworld Explorers",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=54"
                },
                {
                    "id": "55",
                    "name": "119 - Greedy Gift Givers",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=55"
                },
                {
                    "id": "56",
                    "name": "120 - Stacks of Flapjacks",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=56"
                },
                {
                    "id": "57",
                    "name": "121 - Pipe Fitters",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=57"
                },
                {
                    "id": "58",
                    "name": "122 - Trees on the level",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=58"
                },
                {
                    "id": "59",
                    "name": "123 - Searching Quickly",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=59"
                },
                {
                    "id": "62",
                    "name": "126 - The Errant Physicist",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=62"
                }
            ]
        }
    }
}

=== Zacle/practicecoding/test/queries/query/q6.json
{
    "title": "SELECT Codeforces problems that contain 'tree' ",
    "query": "tree",
    "plateform": "codeforces",
    "response": {
        "code": 200,
        "body": {
            "result": [
                {
                    "id": "1010",
                    "name": "F. Tree",
                    "plateform": "Codeforces",
                    "link": "https://codeforces.com/problemset/problem/1010/F"
                },
                {
                    "id": "438",
                    "name": "E. The Child and Binary Tree",
                    "plateform": "Codeforces",
                    "link": "https://codeforces.com/problemset/problem/438/E"
                }
            ]
        }
    }
}
