=== Zacle/practicecoding/test/query.schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "title": "Test Query",
    "description": "A test query and its expected response when passed to Interface.performQuery",
    "type": "object",
    "properties": {
        "title": {
            "description": "A meaningful test name that describes the query",
            "type": "string",
            "minLength": 5,
            "maxLength": 100
        },
        "plateform": {
            "description": "The palteform to query"
        },
        "query": {
            "description": "The query that will be sent to performQuery"
        },
        "response": {
            "description": "The expected response from performQuery",
            "type": "object",
            "properties": {
                "code": {
                    "type": "number"
                },
                "body": {
                    "type": "object"
                }
            },
            "additionalProperties": false,
            "required": ["code", "body"]
        }
    },
    "additionalProperties": false,
    "required": ["title", "query", "plateform", "response"]
}

=== Zacle/practicecoding/test/queries/q15.json
{
    "title": "SELECT Uva problems that contain 'tree' ",
    "query": "tree",
    "plateform": "uva",
    "response": {
        "code": 200,
        "body": {
            "result": [
                {
                    "id": 48,
                    "name": "112 – Tree Summing",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=48"
                },
                {
                    "id": 51,
                    "name": "115 – Climbing Trees",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=51"
                },
                {
                    "id": 58,
                    "name": "122 - Trees on the level",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=58"
                }
            ]
        }
    }
}

=== Zacle/practicecoding/test/queries/filter/q7.json
{
    "title": "SELECT Uva easy problems",
    "query": "easy",
    "plateform": "uva",
    "response": {
        "code": 200,
        "body": {
            "result": [
                {
                    "id": "60",
                    "name": "124 - Following Orders",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=60"
                },
                {
                    "id": "63",
                    "name": "127 - “Accordian” Patience",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=63"
                },
                {
                    "id": "64",
                    "name": "128 - Software CRC",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=64"
                }
            ]
        }
    }
}

=== Zacle/practicecoding/test/queries/q12.json
{
    "title": "SELECT Uva problems that contain 'e' ",
    "query": "e",
    "plateform": "uva",
    "response": {
        "code": 200,
        "body": {
            "result": [
                {
                    "id": 36,
                    "name": "100 – The 3n + 1 problem",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=36"
                },
                {
                    "id": 37,
                    "name": "101 - The Block Problem",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=37"
                },
                {
                    "id": 38,
                    "name": "102 – Ecological Bin Packing",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=38"
                },
                {
                    "id": 39,
                    "name": "103 – Stacking Boxes",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=39"
                },
                {
                    "id": 40,
                    "name": "104 – Arbitrage",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=40"
                },
                {
                    "id": 41,
                    "name": "105 – The Skyline Problem",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=41"
                },
                {
                    "id": 42,
                    "name": "106 – Fermat vs. Pythagoras",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=42"
                },
                {
                    "id": 43,
                    "name": "107 – The Cat in the Hat",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=43"
                },
                {
                    "id": 45,
                    "name": "109 – SCUD Busters",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=45"
                },
                {
                    "id": 46,
                    "name": "110 – Meta-Loopless Sorts",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=46"
                },
                {
                    "id": 48,
                    "name": "112 – Tree Summing",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=48"
                },
                {
                    "id": 49,
                    "name": "113 – Power of Cryptography",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=49"
                },
                {
                    "id": 51,
                    "name": "115 – Climbing Trees",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=51"
                },
                {
                    "id": 52,
                    "name": "116 – Unidirectional TSP",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=52"
                },
                {
                    "id": 53,
                    "name": "117 - The Postal Worker Rings Once",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=53"
                },
                {
                    "id": 54,
                    "name": "118 - Mutant Flatworld Explorers",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=54"
                },
                {
                    "id": 55,
                    "name": "119 - Greedy Gift Givers",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=55"
                },
                {
                    "id": 57,
                    "name": "121 - Pipe Fitters",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=57"
                },
                {
                    "id": 58,
                    "name": "122 - Trees on the level",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=58"
                },
                {
                    "id": 59,
                    "name": "123 - Searching Quickly",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=59"
                },
                {
                    "id": 60,
                    "name": "124 - Following Orders",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=60"
                },
                {
                    "id": 61,
                    "name": "125 - Numbering Paths",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=61"
                },
                {
                    "id": 62,
                    "name": "126 - The Errant Physicist",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=62"
                },
                {
                    "id": 63,
                    "name": "127 - “Accordian” Patience",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=63"
                },
                {
                    "id": 64,
                    "name": "128 - Software CRC",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=64"
                }
            ]
        }
    }
}

=== Zacle/practicecoding/test/queries/query/q13.json
{
    "title": "SELECT Uva problems that contain 'er' ",
    "query": "er",
    "plateform": "uva",
    "response": {
        "code": 200,
        "body": {
            "result": [
                {
                    "id": "42",
                    "name": "106 – Fermat vs. Pythagoras",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=42"
                },
                {
                    "id": "45",
                    "name": "109 – SCUD Busters",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=45"
                },
                {
                    "id": "49",
                    "name": "113 – Power of Cryptography",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=49"
                },
                {
                    "id": "53",
                    "name": "117 - The Postal Worker Rings Once",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=53"
                },
                {
                    "id": "54",
                    "name": "118 - Mutant Flatworld Explorers",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=54"
                },
                {
                    "id": "55",
                    "name": "119 - Greedy Gift Givers",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=55"
                },
                {
                    "id": "57",
                    "name": "121 - Pipe Fitters",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=57"
                },
                {
                    "id": "60",
                    "name": "124 - Following Orders",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=60"
                },
                {
                    "id": "61",
                    "name": "125 - Numbering Paths",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=61"
                },
                {
                    "id": "62",
                    "name": "126 - The Errant Physicist",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=62"
                }
            ]
        }
    }
}

=== Zacle/practicecoding/test/queries/query/q21.json
{
    "title": "SELECT All problems that contain 'tree' ",
    "query": "tree",
    "plateform": "all",
    "response": {
        "code": 200,
        "body": {
            "result": [
                {
                    "id": "1010",
                    "name": "F. Tree",
                    "plateform": "Codeforces",
                    "link": "https://codeforces.com/problemset/problem/1010/F"
                },
                {
                    "id": "438",
                    "name": "E. The Child and Binary Tree",
                    "plateform": "Codeforces",
                    "link": "https://codeforces.com/problemset/problem/438/E"
                },
                {
                    "id": "4",
                    "name": "2003 - Genetic family tree",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=4"
                },
                {
                    "id": "48",
                    "name": "112 – Tree Summing",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=48"
                },
                {
                    "id": "51",
                    "name": "115 – Climbing Trees",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=51"
                },
                {
                    "id": "58",
                    "name": "122 - Trees on the level",
                    "plateform": "Uva",
                    "link": "https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=58"
                }
            ]
        }
    }
}

=== Zacle/practicecoding/test/queries/query/q3.json
{
    "title": "SELECT Codeforces problems that contain 'ere' ",
    "query": "ere",
    "plateform": "codeforces",
    "response": {
        "code": 200,
        "body": {
            "result": [
                {
                    "id": "1036",
                    "name": "E. Covered Points",
                    "plateform": "Codeforces",
                    "link": "https://codeforces.com/problemset/problem/1036/E"
                }
            ]
        }
    }
}

=== Zacle/practicecoding/test/queries/filter/q5.json
{
    "title": "SELECT Live Archive medium problems",
    "query": "medium",
    "plateform": "livearchive",
    "response": {
        "code": 200,
        "body": {
            "result": [
                {
                    "id": "6",
                    "name": "2005 - Message decoding",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=6"
                },
                {
                    "id": "7",
                    "name": "2006 - Most wanted word",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=7"
                },
                {
                    "id": "8",
                    "name": "2007 - Tag Checker",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=8"
                },
                {
                    "id": "9",
                    "name": "2008 - Bouncy Balls",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=9"
                },
                {
                    "id": "14",
                    "name": "2013 - Discrete Digital Tomography",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=14"
                },
                {
                    "id": "15",
                    "name": "2014 - Are We There Yet?",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=15"
                },
                {
                    "id": "16",
                    "name": "2015 - Bob's Bingo Bonanza",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=16"
                },
                {
                    "id": "18",
                    "name": "2017 â€“ Hey  You're Not Marion Jones!",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=18"
                },
                {
                    "id": "27",
                    "name": "2026 - Generating permutations",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=27"
                },
                {
                    "id": "28",
                    "name": "2027 - Island's Vegetation",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=28"
                }
            ]
        }
    }
}

=== Zacle/practicecoding/test/queries/q8.json
{
    "title": "SELECT Live Archive problems that contain 'er' ",
    "query": "er",
    "plateform": "livearchive",
    "response": {
        "code": 200,
        "body": {
            "result": [
                {
                    "id": 2,
                    "name": "2001 - Compiler code generation",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=2"
                },
                {
                    "id": 8,
                    "name": "2007 - Tag Checker",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=8"
                },
                {
                    "id": 15,
                    "name": "2014 - Are We There Yet?",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=15"
                },
                {
                    "id": 24,
                    "name": "2023 - Who Wants to Have the Fastest Fingers?",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=24"
                },
                {
                    "id": 27,
                    "name": "2026 - Generating permutations",
                    "plateform": "Live Archive",
                    "link": "https://icpcarchive.ecs.baylor.edu/index.php?option=onlinejudge&page=show_problem&problem=27"
                }
            ]
        }
    }
}
